In [2]:
import numpy as np
from scipy import sparse
from sys import getsizeof

In [6]:
feature_matrix = np.loadtxt('data/user_feature_matrix.csv', dtype=int, skiprows=1, delimiter=',')

In [9]:
feature_matrix

array([[    1,     0,     1, ...,     0,     0,     0],
       [    2,     0,     0, ...,     0,     0,     0],
       [    3,     0,     1, ...,     0,     0,     0],
       ...,
       [ 9998,     0,     1, ...,     0,     0,     0],
       [ 9999,     0,     0, ...,     0,     0,     0],
       [10000,     0,     0, ...,     0,     0,     0]])

In [10]:
getsizeof(feature_matrix)

120

In [16]:
# no. of elements in the array
feature_matrix.size

66680000

In [14]:
# memory taken up by feature_matrix in MB
feature_matrix.nbytes/(1000*1000)

533.44

In [17]:
sparsity = 1.0 - (np.count_nonzero(feature_matrix)/float(feature_matrix.size))

In [18]:
sparsity

0.9952556388722256

In [19]:
sparse_feature_matrix = sparse.csr_matrix(feature_matrix)

In [24]:
sparse_feature_matrix.size

316354

In [25]:
getsizeof(sparse_feature_matrix)

48

In [27]:
# save sparse CSR matrix
sparse.save_npz('sparse_user_features.npz', sparse_feature_matrix)

In [3]:
# load CSR matrix
sparse_feature_matrix = sparse.load_npz('sparse_user_features.npz')

In [4]:
dataset = sparse_feature_matrix.todense()

In [7]:
dataset.shape

(10000, 6668)

In [10]:
dataset[0][0][0]

matrix([[1, 0, 1, ..., 0, 0, 0]])

In [11]:
np.array(dataset)

array([[    1,     0,     1, ...,     0,     0,     0],
       [    2,     0,     0, ...,     0,     0,     0],
       [    3,     0,     1, ...,     0,     0,     0],
       ...,
       [ 9998,     0,     1, ...,     0,     0,     0],
       [ 9999,     0,     0, ...,     0,     0,     0],
       [10000,     0,     0, ...,     0,     0,     0]])